name: Deploy EC2 Instance

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch
  workflow_dispatch: # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Setup Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6 # Specify your Terraform version

    # Configure AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your preferred AWS region

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Plan Terraform changes
    - name: Terraform Plan
      run: terraform plan

    # Apply Terraform changes
    - name: Terraform Apply
      run: terraform apply -auto-approve
